version: '3.1'

services:

  waf:
    build: waf
    container_name: waf
    environment:
      - ENV=demo
    ports:
        - "80:80"
    volumes:
      - ./waf/log:/var/log/nginx/:rw
      - ./waf/nginx.conf:/etc/nginx/nginx.conf:ro

  app:
      build: app
      container_name: app
      volumes:
        - ./app/public:/usr/src/app/public:ro